# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

def available_pods
    # Define global pods here
end

target 'MovieBooking' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieBooking
  available_pods

  target 'MovieBookingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieBookingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
